# This is a basic workflow to help you get started with Actions

name: UV Pytest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "public/scurri" ]
    paths: ["projects/puzzle3"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./projects/puzzle3
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        # For example, using `pytest`
        run: uv run pytest -v --cov=puzzle3
